# Generated by Django 4.1.1 on 2024-05-13 04:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writting_checker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwrittings',
            name='public_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userwrittings',
            name='writting',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
